blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = "blog"
urlpatterns = [
    url(r'^$', views.BlogListView.as_view(), name="blog-home"),
    url(r'new/$', views.BlogCreateView.as_view(), name="blog-new"),
    url(r'(?P<slug>\S+)/update/$', views.BlogUpdateView.as_view(), name="blog-update"),
    url(r'(?P<slug>\S+)/$', views.BlogDetailView.as_view(), name="blog-detail"),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

portfolio/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from portfolio import views

app_name = "portfolio"
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'about/(?P<name>\S+)/$', views.ProfileView.as_view(), name="profile"),
    url(r'projects/$', views.ProjectListView.as_view(), name="projects"),
    url(r'^(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name="project"),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

portfolio_game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

python_portfolio/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

blog/models.py
from django.db import models
from tinymce.models import HTMLField


class Entry(models.Model):
    author = models.CharField(max_length=144)
    title = models.CharField(max_length=144)
    content = HTMLField('content')
    date_published = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "entries"
        ordering = ['date_published']

    def __unicode__(self):
        return self.title

portfolio/models.py
from django.contrib.auth.models import User
from django.core.validators import EmailValidator
from django.db import models
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=50, null=False)
    email = models.EmailField(validators=[EmailValidator])
    first_name = models.CharField(max_length=44)
    last_name = models.CharField(max_length=44)
    personal_bio = models.TextField()
    professional_bio = models.TextField()
    avatar = models.FileField(upload_to="avatars", null=True)

    def __str__(self):
        return self.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class Project(models.Model):
    name = models.CharField(max_length=144, null=False)
    description = models.TextField()
    type = models.CharField(max_length=20)
    git_link = models.URLField()
    image = models.FileField(upload_to='projects', null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', 'type']

blog/forms.py
from django import forms
from tinymce import TinyMCE

from . import models


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class BlogForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'blog-form-title', 'placeholder': 'Blog Title...'}))
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 5, 'rows': 10}))

    class Meta:
        model = models.Entry
        fields = ['title', 'content']

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView, CreateView
from slugify import slugify

from . import forms
from . import models


# Blog form for easily creating blog by authorized user
class BlogCreateView(CreateView):
    model = models.Entry
    template_name = "blog/blog_new.html"
    form_class = forms.BlogForm

    def post(self, request, *args, **kwargs):
        form = forms.BlogForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = "Paul Jenkins"
            post.slug = slugify(post.title)
            post.save()
            return HttpResponseRedirect(reverse('blog:blog-detail', kwargs={'slug': post.slug}))
        else:
            form = forms.BlogForm()
        return render(request, 'blog/blog_new.html', {'form': form})


# Blog edit page
class BlogUpdateView(UpdateView):
    model = models.Entry
    template_name = "blog/blog_new.html"


# Blog Home page, blogs context for navigation menu
class BlogListView(TemplateView):
    model = models.Entry
    template_name = "blog/blog_home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blogs'] = models.Entry.objects.all()
        return context


# Blog matches slug- Details for that blog, blogs used for navigation menu
class BlogDetailView(TemplateView):
    model = models.Entry
    template_name = "blog/blog_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blogs'] = models.Entry.objects.all()
        context['blog'] = models.Entry.objects.get(slug=kwargs['slug'])
        return context

portfolio/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


from . import models


# Home page, no need for class view, no model used on this page
def home(request):
    return render(request, 'portfolio/home.html')


# ProfileView- TemplateView- class view, used Profile model to show user profile info
class ProfileView(TemplateView):
    model = models.Profile
    template_name = 'portfolio/about-me.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = models.Profile.objects.get(first_name=kwargs['name'])
        return context


# Projects home page- model used to build navigation menu of all projects created
class ProjectListView(TemplateView):
    model = models.Project
    template_name = 'portfolio/project_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = models.Project.objects.all()
        return context


# Project Detail page display particular project- projects used for navigation menu
class ProjectDetailView(TemplateView):
    model = models.Project
    template_name = 'portfolio/project_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = models.Project.objects.get(pk=kwargs['pk'])
        context['projects'] = models.Project.objects.all()
        return context

templates/blog/blog_detail.html
{% extends 'blog/blog_layout.html' %}
{% load static %}
{% block title %}Blog | {{ blog.title }}{% endblock %}

{% block content %}
    <div class="blog-entry">
        <div id="blog-entry-header">
            <h1>{{ blog.title }}</h1>
            <p>By: {{ blog.author }}</p>
            <p><em>posted: {{ blog.date_published }}</em></p>
        </div>
        <div id="blog-entry-content">
            <p>{{ blog.content|safe }}</p>
        </div>
    </div>

{{ block.super }}
{% endblock %}

templates/blog/blog_home.html
{% extends 'blog/blog_layout.html' %}

{% block title %}Blog{% endblock %}

{% block content %}

    <div class="blog-entry">
        <div id="blog-entry-header">
            <h1>Blog</h1>
            <h3>
                Welcome to my blog page!
            </h3>
            <p>
                Here you'll find various projects that I've worked on over the last year or so.
                I've built programs using Python as my base language, but that has carried over into
                projects built in Django and Flask.
                I've also incorporated JavaScript (including JQuery) and CSS in many of these projects
                as well as this portfolio.
                If you have any questions, concerns, or comments, please contact me.
            </p>
        </div>
    </div>
        {{ block.super }}
{% endblock %}

templates/blog/blog_layout.html
{% extends 'portfolio/layout.html' %}
{% load static %}
{% static "" as baseURL %}

{% block title %}{% endblock %}
{% block content %}
    <div class="nav-wrapper">
        <div class="nav-menu-container">
            <div class="left-arrow">
                <a href="#prev">
                    <img id="left-arrows" src="{% static 'images/left-arrow.jpg' %}">
                </a>
            </div>
            <div class="nav-menu">
                {% for item in blogs %}
                    <a href="{% url 'blog:blog-detail' slug=item.slug %}">
                        <img class="nav-menu-item" id="{{ item.slug }}"
                             src="{% static 'images' %}/{{ item.slug }}.jpg"></a>
                {% endfor %}
            </div>
            <div class="right-arrow">
                <a href="#next">
                    <img id="right-arrows" src="{% static 'images/right-arrow.jpg' %}">
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/blog_new.html
{% extends 'blog/blog_layout.html' %}
<head>


    {% block title %}Blog | NEW{% endblock %}

    {% block content %}

        <div class="blog-form">

            <form method="POST" action="">
                <h1>New Blog Post</h1>
                {% csrf_token %}
                {{ form.media }}
                <p>{{ form.title.label }}: {{ form.title }}</p>
                <p>{{ form.content }}</p>
                <input type="submit" value="submit" class="blog-form-button">
            </form>
        </div>
    {% endblock %}

templates/portfolio/about-me.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block title %}About | Paul{% endblock %}


{% block content %}
    <div class="profile-container">
        <h1 style="text-align: center; border-bottom: 1px solid black;">Meet {{ profile.first_name }}</h1>
        <div class="avatar-social">
            <img class="avatar" src="{% static 'images' %}/{{ profile.avatar.url }}">
            <div id="social-media" style="padding: 10px;">
                <a href="https://www.twitter.com/jnkn315" target="_blank"><img
                        src="{% static 'images/icons/Twitter_Logo_Blue.png' %}"></a>
                <a href="https://www.github.com/paulojenks" target="_blank"><img
                        src="{% static 'images/icons/Git-Icon-Black.png' %}"></a>
                <a href="https://www.linkedin.com/in/paul-jenkins-48882670/" target="_blank"><img
                        src="{% static 'images/icons/LI-In-Bug.png' %}"></a>
                <a href="https://www.facebook.com" target="_blank"><img
                        src="{% static 'images/icons/f_logo_RGB-Blue_250.png' %}"></a>
            </div>
        </div>
        <div class="bio-container">
            <h4>About Paul</h4>
            <p>{{ profile.personal_bio }}</p>
            <h4>Professional Bio:</h4>
            <p>{{ profile.professional_bio|safe }}</p>
        </div>
    </div>
{% endblock %}

templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}
{% load static %}
{% static "" as baseURL %}

{% block title %}Paul Jenkins{% endblock %}
{% block content %}

    <div class="display-wrapper">
        <div class="display">
            <a href="{% url 'portfolio:projects' %}"><img class="display-img"
                                                              src="{% static 'images/projects-lg.jpg' %}"></a>
            <a href="{% url 'blog:blog-home' %}"><img class="display-img"
                                                      src="{% static 'images/blog-lg.jpg' %}"></a>
            <a href="{% url 'portfolio:profile' name="Paul" %}"><img class="display-img"
                                                         src="{% static 'images/about-me-lg.jpg' %}"></a>
        </div>

    </div>
    <div class="nav-wrapper">
        <div class="nav-menu-container">
            <div class="left-arrow">
                <a href="#prev">
                    <img src="{% static 'images/left-arrow.jpg' %}">
                </a>
            </div>
            <div class="nav-menu">
                <img class="nav-menu-item" id="projects" src="{% static 'images/projects.jpg' %}"
                     onclick="currentDiv(1)">
                <img class="nav-menu-item" id="blog" src="{% static 'images/blog.jpg' %}"
                     onclick="currentDiv(2)">
                <img class="nav-menu-item" id="about-me" src="{% static 'images/about-me.jpg' %}"
                     onclick="currentDiv(3)">
            </div>
            <div class="right-arrow">
                <a href="#next">
                    <img src="{% static 'images/right-arrow.jpg' %}">
                </a>
            </div>
        </div>
    </div>
    <script>

    </script>
{% endblock %}

templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
{% static "" as baseURL %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="text/javascript" href="{% static '/js/main.js' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'js/main.js' %}"></script>
    <script>

        function onHover() {
            let srcId = event.srcElement.id;
            let locId = "images/" + srcId + "-white.jpg";
            $("#" + srcId).attr('src', '{{ baseURL }}' + locId);
        }

        function offHover() {
            let srcId = event.srcElement.id;
            let locId = "images/" + srcId + ".jpg";
            $("#" + srcId).attr('src', '{{ baseURL }}' + locId);
        }

        function currentDiv(n) {
        showDivs(slideIndex = n);
    }
        let slideIndex = 1;
        showDivs(slideIndex);

        function showDivs(n) {
            let i;
            let x = document.getElementsByClassName("display-img");
            let dots = document.getElementsByClassName("nav-menu-item");
            if (n > x.length) {
                slideIndex = 1
            }
            if (n < 1) {
                slideIndex = x.length
            }
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
            }
            x[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " w3-opacity-off";
        }
    </script>
</head>
<body>
<div id="background" style="background-image: url('{% static 'images/mooning.png' %}')">
    <div id="top-bar">
        <div id="logo"><p><a href="{% url 'portfolio:home' %}"><img src="{% static 'images/icons/home.jpg' %}" >  | Official Site of Paul Jenkins</a></p></div>
    </div>
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/portfolio/project_detail.html
{% extends 'portfolio/projects.html' %}
{% load static %}
{% block title %}{{ project.type }} | {{ project.name }}{% endblock %}

{% block content %}
    <div class="display-wrapper">
        <div class="blog-entry">
            <div id="blog-entry-header">
                <h1>{{ project.name }}</h1>
                <p>{{ project.type }}</p>
                <p><em>GitHub: <a href="{{ project.git_link }}">{{ project.git_link }}</a></em></p>
            </div>
            <div id="blog-entry-content">
                <p>{{ project.description|safe }}</p>
            </div>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

templates/portfolio/project_list.html
{% extends 'portfolio/projects.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <div class="blog-entry">
        <div id="blog-entry-header">
            <h1>Projects</h1>
            <h3>
                Welcome to my project showcase page!
            </h3>
            <p>
                Here you'll find various projects that I've worked on over the last year or so.
                I've built programs using Python as my base language, but that has carried over into
                projects built in Django and Flask.
                I've also incorporated JavaScript (including JQuery) and CSS in many of these projects
                as well as this portfolio.
                If you have any questions, concerns, or comments, please contact me.
            </p>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

templates/portfolio/projects.html
{% extends 'portfolio/layout.html' %}
{% load static %}
{% static "" as baseURL %}

{% block content %}
    <div class="nav-wrapper">
        <div class="nav-menu-container">
            <div class="left-arrow">
                <a href="#prev">
                    <img id="left-arrows" src="{% static 'images/left-arrow.jpg' %}">
                </a>
            </div>
            <div class="nav-menu">

                {% for project in projects %}
                    <a href="{% url 'portfolio:project' pk=project.id %}">
                        <img class="nav-menu-item" id="{{ project.name }}"
                             src="{% static 'images/' %}{{ project.image.url }}">
                    </a>
                {% endfor %}
            </div>
            <div class="right-arrow">
                <a href="#next">
                    <img id="right-arrows" src="{% static 'images/right-arrow.jpg' %}">
                </a>
            </div>
        </div>
    </div>
{% endblock %}